
services:
  arenaqa:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
    restart: unless-stopped
